// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace ceat.Sources
{
	public partial class CauseEffecetMatrixViewController : NSViewController
	{
		public CauseEffecetMatrixViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
